
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.0
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: on-failure:0
    environment:
      # QUERY_DEFAULTS_LIMIT: "20"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"   # dev-режим
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      # включаем модуль и задаём его URL
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://text2vec-transformers:8080"
    volumes:
      - ./data:/var/lib/weaviate
    depends_on:
      - text2vec-transformers
    networks:
      - weaviate-net

  text2vec-transformers:
    # готовый образ с моделями sentence-transformers
    image: semitechnologies/transformers-inference:qwen-qwen3-embedding-0.6b
    environment:
      ENABLE_CUDA: "1"
      NVIDIA_VISIBLE_DEVICES: "all"
    # runtime: nvidia
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - weaviate-net


networks:
  weaviate-net:
    driver: bridge